### ISSUE TITLE
Update Data Storage Screen

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/at_data_browser#12]
**Data Storage** + **atSigns** + **Apps**
![Screenshot 2023-05-24 at 9 20 12 PM](https://github.com/atsign-foundation/at_data_browser/assets/84993403/bca829c1-2daf-40c2-b6e8-4cba13870757)
- [x] Only show "Add filter" after a filter has been defined
- [x] Change "Browse" -> Data Storage 
- [x] Have title left-aligned
- [x] Make "Item stored" text smaller & allow for some padding (see (see [Figma](https://www.figma.com/file/734L9TPXqQjcxx5olcERrb/atDataBrowser?type=design&node-id=30%3A1076&t=h5jkmbFe9HOPQ2py-1))
- [x] Empty states: Add box (see [Figma](https://www.figma.com/file/734L9TPXqQjcxx5olcERrb/atDataBrowser?type=design&node-id=30%3A1076&t=h5jkmbFe9HOPQ2py-1))
- [x] Make background more pale #EDF4F5
- [x] Add left padding to list
- [x] Make font regular instead of medium
- [x] #17
- [x] Dropdown of cards: follow grey design Frame #38 
- [x] When atKey/atValue/metaData is selected (follow design): titles blue and font is smaller than data

**Comment by CurtlyCritchlow** [comment]
@kzawadi I closed #13 and I fixed "Only show "Add filter" after a filter has been defined" since it was related to the search function.

**Comment by kzawadi** [comment]
Fine and I just noted I ticked and no PR. I will  do that by today

**Comment by CurtlyCritchlow** [comment]
No, do the PR when you complete all the tasks. Just ensure you update ur branch with the latest changes in trunk.

**Comment by kzawadi** [comment]
oh okay..
