### ISSUE TITLE
Remove arrows

### ISSUE THREAD

**Issue by kzawadi** [atsign-foundation/at_data_browser#17]

**Comment by kzawadi** [comment]
it seems like it isn't easy to remove the trailing icon in `ExpansionPanel`.There is an open issue to fix this on the Flutter repository (https://github.com/flutter/flutter/issues/108973). or alternatively to modify a local version of Flutter that is not clean at all. @CurtlyCritchlow What do you think?

**Comment by CurtlyCritchlow** [comment]
We'll have to leave it as is or build our own widget.

**Comment by kzawadi** [comment]
I suggest leaving it as it is for now...
