### ISSUE TITLE
at_data_browser Architecture

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/at_data_browser#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Address the following before app design continues:

- [x] How to identify a bad data?
- [x] How to identify a malformed atKey?
- [x] What are the type of keys?
- [x] Should at_browser delete atKeys?
- [x] Should at_browser edit atKeys?
- [x] What atKeys type are editable?
- [x] What atKey properties can be edited?

**Describe alternatives you've considered**

**Additional context**

**Comment by VJag** [comment]
**How to identify bad data** - Bad data can be defined from the perspective of SDK and the app

**SDK perspective:** SDK could not return a AtValue from a get() on atClient. There could be several reasons for this. SDK should throw an exception when a AtValue could not be returned. 

**App perspective:** Could be data created by mistake, misspelled data, etc..

**How to identify a malformed atKey** - SDK should have a method for it. @sitaram-kalluri can use AtKey.getType() that takes a string for it?

**What are the type of keys**: public, self, shared, private there is an enumeration in SDK that lists all key types

**Should at_browser delete atKeys**: I think yes

**Should at_browser edit atKeys**: No I think. We can add this functionality in V2. But let's take the opinion of the rest of the team.

**What atKeys type are editable?** : Depends on the answer to the above question.

**What atKey properties can be edited?**: Depends on the answer to the above question.

**Comment by sitaram-kalluri** [comment]
To identify a malformed key use `AtKey.getKeyType(String atKey)` method.

Example:

```
var keyType = AtKey.getKeyType('public:phone@bob', enforceNameSpace: true);
```
The above returns `KeyType.invalidKey`. Please refer to the following link for various [key-types](https://github.com/atsign-foundation/at_tools/blob/trunk/packages/at_commons/lib/src/keystore/key_type.dart)


Following are the exceptions thrown when fetching the key using AtClient.get method

* Throws [AtKeyException] for the invalid key formed
* Throws [AtDecryptionException] if fails to decrypt the value
* Throws [AtPrivateKeyNotFoundException] if the encryption private key is not found to decrypt the value
* Throws [AtPublicKeyChangeException] if the encryption public key used encrypt the value is different from the current encryption public key(at the time of decryption)
* Throws [SharedKeyNotFoundException] if the shared key to decrypt the value is not found
* Throws [SelfKeyNotFoundException] if the self-encryption key is not found.
* Throws [AtClientException] if the cloud secondary is invalid or not reachable

Please refer to the following link for the [AtClient.get()](https://github.com/atsign-foundation/at_client_sdk/blob/993ff11e0150e01591e6c68bab85fe4e55b92660/packages/at_client/lib/src/client/at_client_spec.dart#L167) usage

**Comment by CurtlyCritchlow** [comment]
Thank you, @VJag and @sitaram-kalluri for the answers. What key type should not be deleted by at_browser, ie they should be view only?

**Comment by CurtlyCritchlow** [comment]
[Documentation](https://docs.atsign.com/sdk/flutter/key_basics/) to understand atKeys

**Comment by sitaram-kalluri** [comment]
> Thank you, @VJag and @sitaram-kalluri for the answers. What key type should not be deleted by at_browser, ie they should be view only?

@CurtlyCritchlow: All the reserved keys in the above documentation should not be deleted/updated.

**Comment by CurtlyCritchlow** [comment]
@Dariamarg Here's an example of the an atKey and atValue broken down into it's various properties.


AtKey: @bob:52984fc7-a349-89e1-afcf-daa86g602c4d.at_dude@alice
  isRef: false
  key: 52984fc7-a349-89e1-afcf-daa86g602c4d
  hashCode: 424163146
  isLocal: false
  namespace: "at_dude"
  runtimeType: Type (AtKey)
  sharedBy: "@alice"
  sharedWith: "@bob
  metaData: 
    availableAt: DateTime (2023-03-06 12:50:46.415Z)
    ccd: false
    createdAt: DateTime (2023-03-06 12:50:46.415Z)
    dataSignature: null
    encAlgo: null
    encoding: null
    expiresAt: null
    fullJson: true
    isBinary: false
    isCached: false
    isEncrypted: true
    isHidden: false
    isPublic: false
    ivNonce: null
    namespaceAware: true
    pubKeyCS: 3b434c6c0d33105f9fc7c72ef6461a91
    refreshAt: null
    sharedKeyEnc: cHi7XUJnQItEblR+/++gk9eqNjua0ucnJdd... (a 344 length string)
    sharedKeyStatus: null
    skeEncAlgo: null
    skeEncKeyName: null
    ttb: 0
    ttl: 0
    ttr: -1
    updatedAt: DateTime (2023-04-06 12:50:46.415Z)
    hashCode: 531741941
    runtimeType: Type(Metadata)

AtValue{
  value: {
    "id":"52984fc7-a349-89e1-afcf-daa86g602c4d",
    "sender":"@alice",
    "receiver":"@bob",
    "timeSent":"2023-03-05T16:06:09.697202Z",
    "selectedDudeType":"hi",
    "isRead":false
  }, 
  metadata: 
    Metadata{
      ttl: 0, 
      ttb: 0, 
      ttr: -1,
      ccd: false, 
      isPublic: false, 
      isHidden: false, 
      availableAt : 2023-03-06 12:50:46.415Z, 
      expiresAt : null, 
      refreshAt : null, 
      createdAt : 2023-03-06 12:50:46.415Z, 
      updatedAt : 2023-03-06 12:50:46.415Z, 
      isBinary : false, 
      isEncrypted : true, 
      isCached : false, 
      dataSignature: null, 
      sharedKeyStatus: null, 
      encryptedSharedKey: cHi7XUJnQItEblR+/++gk9eqNjua0ucnJdd..., (a 344 length string) 
      pubKeyCheckSum: 3b434c6c0d33105f9fc7c72ef6461a91, 
      encoding: null, 
      encKeyName: null, 
      encAlgo: null, 
      ivNonce: null, 
      skeEncKeyName: null, 
      skeEncAlgo: null
    }
  }
