### ISSUE TITLE
bug on depricated fields on at_onboarding_flutter 

### ISSUE THREAD

**Issue by kzawadi** [atsign-foundation/at_data_browser#27]
**Describe the bug**
seems like we are using a package that has deprecated fields.
The package is [at_onboarding_flutter] version 6.0.3

**To Reproduce**
1. First I 'clone the current trunk'
2. Then I 'then run flutter pub get'
3. And then 'after dart analysis is over you will see the errors like Text(AtOnboardingStrings.resetDescription)'
4. 

**Expected behavior**
we should have n errors after pub get especially after pulling from the main trunk.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  - [e.g. @‎buzz, @‎tmosphere]

**Additional context**

**Comment by CurtlyCritchlow** [comment]
The depreciated fields aren't used by the package anymore
