### ISSUE TITLE
at_data_browser UI design

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/at_data_browser#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Discuss and build the UI of the app based on findings on the  at_data_browser architecture discussion, 

**Describe alternatives you've considered**

**Additional context**

**Comment by ksanty** [comment]
Design for MVP design 1st before we jump into too much design.

**Comment by Dariamarg** [comment]
Here is the [Figma](https://www.figma.com/file/734L9TPXqQjcxx5olcERrb/atDataBrowser?node-id=0%3A1&t=6q6fgtGEUUU6zBua-1)
