### ISSUE TITLE
July 13 - Enhancements

### ISSUE THREAD

**Issue by Dariamarg** [atsign-foundation/at_data_browser#31]
- [x] background and header are two different colours (if we can make them both the grey) 
![IMG_8883](https://github.com/atsign-foundation/at_data_browser/assets/84993403/3e162114-f987-4ba3-aa6c-b1af58b64c11)
- [x] Make app accent colour the blue: #57A8B5 (for example in loading icons, onboarding...)
![IMG_8884](https://github.com/atsign-foundation/at_data_browser/assets/84993403/9ef7ddd2-499c-4df0-90c1-f4fa791ab67f)
- [x] Add a little bit of a margin on the left side as it is really close to screen
![IMG_8886](https://github.com/atsign-foundation/at_data_browser/assets/84993403/0258c7eb-f7c7-4f76-a6ec-4986593241df)
- [x] Can we decrease font size to match the rest?
![IMG_8887](https://github.com/atsign-foundation/at_data_browser/assets/84993403/8c50b41e-9780-4e2b-8f6d-8587d7722cb9)
- [x] One loading should be good (don't know if this is a bug)
![IMG_8888](https://github.com/atsign-foundation/at_data_browser/assets/84993403/98f5fb01-73f8-46aa-90ee-03b6caa97a7f)
- [x] Can we make all the sizing of search text the same (right-hand components have varying sizes)
![IMG_8890](https://github.com/atsign-foundation/at_data_browser/assets/84993403/316ab88c-6c47-44b4-8467-abc4c5b60564)
- [x] Instead of the purple can we get the blue (#57A8B5) for this screen and the atSign one (#E46B48), Namespaces (#E8B74E)
![IMG_8889](https://github.com/atsign-foundation/at_data_browser/assets/84993403/c0c77591-a34e-4070-9bd7-c78e3f89d650)

**Comment by CurtlyCritchlow** [comment]
@Dariamarg 

- Can we decrease font size to match the rest - The screenshot is in keeping with the Figma design... to clarify you want for example "namespace" and "buzz" to be the same font size?

**Comment by CurtlyCritchlow** [comment]
- [x] Add Filter button show even if the user didn't apply any filter. Add Filter button should only show on the UI if the user apply the filter.

**Comment by Dariamarg** [comment]
@CurtlyCritchlow no no the text when the card is expanded to details is really big, if we can match the size of @misstremendous (card) to be the size of "buzz" and have name space 2-3 points smaller (whatever is legible)
