### ISSUE TITLE
Enhancements - May 23 (Daria)

### ISSUE THREAD

**Issue by Dariamarg** [atsign-foundation/at_data_browser#8]
Notes on UI discrepancies:

**General:**
- [ ] Font; Poppins?
- [ ] Background #F9F9F9

**Settings**
![IMG_7800](https://github.com/atsign-foundation/at_data_browser/assets/84993403/7c834342-f2b3-47cb-8b5d-6b4e5f02f376)
- [ ] Make card longer
- [ ] Tittle

**Home Screen**
![Screenshot 2023-05-23 at 1 40 53 AM](https://github.com/atsign-foundation/at_data_browser/assets/84993403/44379c27-09dc-430a-afe1-f4112ba0ca0f)
- [ ] Background Colour #F9F9F9
- [ ] Vertically-Center titles for "Data Storage", "atSigns", "Apps"
- [ ] Add a margin on the left for titles of "Data Storage", "atSigns", "Apps" 
- [ ] Make titles of "Item Stored", "Connected atSigns", "Connected Apps" font a little smaller and have last 2 on two lines
- [ ] Make "Settings Icon a little larger
- [ ] "DataBrowser": Make it bigger and have Data part bolder - Poppins and Browser part Regular (also add more of a margin on the left)

**Data Storage** + **atSigns** + **Apps**
![Screenshot 2023-05-24 at 9 20 12 PM](https://github.com/atsign-foundation/at_data_browser/assets/84993403/bca829c1-2daf-40c2-b6e8-4cba13870757)
- [ ] Only show "Add filter" after a filter has been defined
- [ ] Change "Browse" -> Data Storage 
- [ ] Have title left-aligned
- [ ] Make "Item stored" text smaller & allow for some padding (see (see [Figma](https://www.figma.com/file/734L9TPXqQjcxx5olcERrb/atDataBrowser?type=design&node-id=30%3A1076&t=h5jkmbFe9HOPQ2py-1))
- [ ] Empty states: Add box (see [Figma](https://www.figma.com/file/734L9TPXqQjcxx5olcERrb/atDataBrowser?type=design&node-id=30%3A1076&t=h5jkmbFe9HOPQ2py-1))
- [ ] Make background more pale #EDF4F5
- [ ] Add left padding to list
- [ ] Make font regular instead of medium
- [ ] Remove arrows
- [ ] Dropdown of cards: follow grey design Frame #38 
- [ ] When atKey/atValue/metaData is selected (follow design): titles blue and font is smaller than data
**Search Function**
- [ ] Less Radius on boxes
- [ ] Have boxes take up more space (and keep them consistent between options) - options can probably 

_Food for Thoughts_
- [ ] Might need a search icon (?)
- [ ] If screen is too small (might need to stack options) (?)

**Comment by Dariamarg** [comment]
Animation:

- [ ] Skeleton load
- [ ] Drawer opening

**Comment by CurtlyCritchlow** [comment]
I'v created separate tickets for each screen. I'll close this issue.
